// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PriceEventyIF is an autogenerated mock type for the PriceEventyIF type
type PriceEventyIF struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *PriceEventyIF) Close() {
	_m.Called()
}

// SendPriceEvent provides a mock function with given fields: message
func (_m *PriceEventyIF) SendPriceEvent(message []byte) {
	_m.Called(message)
}

// NewPriceEventyIF creates a new instance of PriceEventyIF. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPriceEventyIF(t interface {
	mock.TestingT
	Cleanup(func())
}) *PriceEventyIF {
	mock := &PriceEventyIF{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
