// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// ProductHandlerIF is an autogenerated mock type for the ProductHandlerIF type
type ProductHandlerIF struct {
	mock.Mock
}

// UpdatePrice provides a mock function with given fields: context
func (_m *ProductHandlerIF) UpdatePrice(context echo.Context) error {
	ret := _m.Called(context)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePrice")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(context)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewProductHandlerIF creates a new instance of ProductHandlerIF. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductHandlerIF(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductHandlerIF {
	mock := &ProductHandlerIF{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
